"""Receiver identity verification via Didit, and the free-tier quota that meters it.

FP-155 records what the receiver TYPED. This records whether that identity was checked,
by whom, and what came back — or, far more often than is comfortable, exactly why it
could not be.

What is deliberately NOT here is the point of the design. No document image, no face
image, no ID number extracted by the vendor. Didit holds those; we hold a decision and a
session reference, which is what the architecture doc means by "does not replicate
identity data". The cost is real and is recorded in the spec: in a dispute the underlying
images must be re-queried from the vendor rather than read locally.
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.models import Base
from app.db.models.enums import (
    ReceiverVerificationStatus,
    ReceiverVerificationTier,
    ReceiverVerificationUnverifiedReason,
)


class ReceiverIdentityVerification(Base):
    """One identity check against one handover confirmation.

    Keyed on the capability token rather than the confirmation, because the spec's
    ordering is verify-then-confirm: this row exists before the receiver signs. The
    unique constraint on token_id is what makes "one verification per grant" true at
    the database rather than at the application's word.
    """

    __tablename__ = "receiver_identity_verifications"
    __table_args__ = (
        # Keyed on the TOKEN, not the confirmation. The spec's ordering (§6) is
        # verify-then-confirm: this row is created when the receiver consents, which is
        # before they sign and therefore before any handover_confirmations row exists.
        # The token is the only identifier that exists for the whole exchange.
        UniqueConstraint("token_id", name="uq_receiver_identity_verifications_token_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # The grant this verification was performed against. Non-null and unique: a
    # verification with no token did not come from a scan, and one token yields at most
    # one verification.
    token_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("handover_capability_tokens.id"), nullable=False
    )
    # Filled in at confirm time, not at creation. NULL is the ordinary state for a
    # verification whose receiver has not signed yet — and the permanent state for one
    # who verified and then walked away, which is itself part of the record.
    handover_confirmation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("handover_confirmations.id"), nullable=True
    )
    # Denormalised off the confirmation so a dispatcher's trip view resolves a
    # verification with one row read, matching what HandoverCapabilityToken does with
    # trip_id for the same reason.
    trip_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("trips.id"), nullable=False)

    status: Mapped[ReceiverVerificationStatus] = mapped_column(String(20), nullable=False)
    tier: Mapped[ReceiverVerificationTier] = mapped_column(String(20), nullable=False)
    unverified_reason: Mapped[Optional[ReceiverVerificationUnverifiedReason]] = mapped_column(
        String(30), nullable=True
    )

    # Recorded even though only one provider exists today, so a future swap leaves old
    # rows legible about which vendor actually produced their verdict.
    provider: Mapped[str] = mapped_column(String(20), nullable=False)
    # Generated by us and persisted BEFORE the receiver is redirected. The client never
    # gets to name a session, which is what stops it substituting somebody else's
    # approved one — see the spec's "never trust the browser" rule.
    provider_session_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    provider_decision_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Whether the vendor's extracted identity agreed with what the receiver typed. NULL
    # when no document data exists to compare (every tier below DOCUMENT_AND_FACE).
    # False is the substitution signal: a single-use link stops replay, not a confederate
    # completing the flow with their own genuine ID before the receiver opens it.
    identity_match: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)

    # SELFIE_ONLY tier only. Our own capture, stored in af-south-1 like every other
    # artifact — never sent to the vendor, so it never enters the s26 biometric regime.
    selfie_artifact_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("evidence_artifacts.id"), nullable=True
    )

    # POPIA s27(1)(a). Biometric processing is prohibited without an exemption, and
    # explicit consent is the one we rely on — so the consent is evidence in its own
    # right. The HASH, not the text: it proves WHICH wording was agreed to without
    # duplicating the copy into every row, which is what makes the wording versioned
    # content rather than a UI string somebody edits freely.
    consent_given_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    consent_text_hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # A webhook that lands after this row terminalised does NOT move `status` — that
    # would break the spec's invariant and let a closed trip be rewritten. It is kept
    # here instead, following the rule the rest of this codebase applies to every
    # inconvenient finding: record it, do not refuse it and forget it happened.
    late_decision_status: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    late_decision_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class IdvsQuotaLedger(Base):
    """How many free vendor sessions this calendar month has already spent.

    One row per (period, provider). The team's decision is a HARD stop: at the limit we
    stop calling the vendor and degrade the handover, rather than letting session 501
    silently bill. That makes this row a spending control, not a statistic.

    `period` is UTC, and the comment matters more than the column: Didit resets its free
    quota at 00:00 UTC, which is 02:00 SAST. Keying this on local time would roll the
    counter two hours late every month and bill for the gap.
    """

    __tablename__ = "idvs_quota_ledger"
    __table_args__ = (
        UniqueConstraint("period", "provider", name="uq_idvs_quota_ledger_period_provider"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # "YYYY-MM", UTC. A string rather than a date because the whole month is the unit;
    # storing a date would invite a range query that gets the boundary wrong.
    period: Mapped[str] = mapped_column(String(7), nullable=False)
    provider: Mapped[str] = mapped_column(String(20), nullable=False)
    sessions_used: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
