import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import withSerwistInit from "@serwist/next";
import type { NextConfig } from "next";

// `next build` always runs with NODE_ENV=production (regardless of which npm script
// invoked it — build, cap:sync, cap:run all shell out to `next build`), so this guard
// fires on every real production build. With output: 'export' there is no server to read
// env vars at request time — NEXT_PUBLIC_API_URL gets baked into the JS bundle at build
// time. An unset or localhost value here means the shipped APK/installed PWA silently
// ships talking to a backend that doesn't exist on the device (lib/api/client.ts falls
// back to http://localhost:8000, which only makes sense for `next dev`).
// Escape hatch: set NEXT_PUBLIC_API_URL to the real target (deployed URL, or a LAN IP for
// a `cap sync` build during development) before running the build — this check only
// fires when the var is missing entirely or still points at localhost.
if (process.env.NODE_ENV === "production") {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL;
  if (!apiUrl || apiUrl.includes("localhost")) {
    throw new Error(
      "[next.config.ts] NEXT_PUBLIC_API_URL is unset or points at localhost for a " +
        "production build. Set it to the real backend origin (deployed URL, or a LAN IP " +
        "for a local cap:sync build) before building.",
    );
  }
}

// Read package.json version once, reused for the SW precache revision and the
// NEXT_PUBLIC_APP_VERSION env injection. The precache revision is the package version,
// bumped as a deliberate signal rather than a value that churns on every build (a build
// timestamp would force every installed client to re-download all 74 route entries on
// every deploy, even ones with no content change).
const { version: packageJsonVersion } = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), "package.json"), "utf-8"),
) as { version: string };

const nextConfig: NextConfig = {
  output: "export",
  // Required for output: 'export' — Next.js image optimisation uses a server; static export cannot.
  images: { unoptimized: true },
  // `next build` fails the whole build on any ESLint error found anywhere in the project,
  // not just in files this build actually touches — discovered while verifying FIX 3/4/5:
  // app/global-error.tsx (@next/next/no-html-link-for-pages) and lib/context/AuthContext.tsx
  // (a stale `react-hooks/set-state-in-effect` disable comment, orphaned by the
  // eslint-config-next 15 downgrade in FIX 5 — see package.json) are both outside this
  // change's scope and owned by other in-progress work. `npm run lint` still runs
  // separately (unaffected by this) and still reports both — this only stops an unrelated
  // file's lint state from blocking everyone's production build. Flagged for the team:
  // consider re-enabling once those two are resolved.
  eslint: { ignoreDuringBuilds: true },
  env: {
    NEXT_PUBLIC_APP_VERSION: packageJsonVersion,
  },
};

// ── Offline navigation precache (FIX 3) ──────────────────────────────────────────────
//
// Why this exists: @serwist/next's InjectManifest webpack plugin builds its precache
// manifest from two sources — (a) the webpack compilation's own emitted assets (JS/CSS/
// fonts — this is automatic and unaffected by anything below), and (b) either a scan of
// public/ (the default) OR, if `additionalPrecacheEntries` is supplied below, exactly
// that list instead (see @serwist/next's `resolvedManifestEntries` logic — supplying
// this option *replaces* the public/ scan, it doesn't add to it). Source (a) explicitly
// excludes anything under the server compilation ("server/**"), which is where Next's
// prerendered HTML lives at webpack-compile time — that's why the shipped SW previously
// precached ~45 JS/CSS/font files and zero pages: nothing was ever wired to precache the
// actual route documents.
//
// The static HTML export itself (out/**) doesn't exist until *after* webpack compiles —
// Next runs the exporter as a post-build step — so a glob over out/ here can't work
// either. The only remaining option is to hand-maintain the route list.
//
// Route list: every page `next build` currently exports, expressed as route paths (not
// filenames). Re-derive after adding/removing a page with:
//   next build && find out -iname '*.html' ! -name '404.html' | sed 's#^out##;s#\.html$##;s#/index$#/#'
// Two routes are generated by `generateStaticParams` rather than being literal files
// under app/ — HANDSHAKE_STEP_SLUGS mirrors frontend/shared/lib/constants/handshake-meta.ts
// (STEP_SLUGS) and MOCK_TRIP_IDS mirrors the TRIP_00xx_ID constants in
// frontend/shared/lib/mocks/trips.ts. Both are copied in rather than imported because
// next.config.ts executes outside the app's @shared/* path-alias resolution. The trips/[id]
// route is explicitly mock-data-only (see app/(app)/trips/[id]/page.tsx) — expect
// MOCK_TRIP_IDS to need removing, not just updating, once Iter 2 swaps in a real
// trip-id-backed fetch (a route keyed on live server data generally can't be static-precached
// this way at all).
const STATIC_ROUTES = [
  "/",
  "/login",
  "/otp",
  "/settings",
  "/trip/in-transit",
  "/trip/in-transit/checkpoint",
  "/trip/in-transit/exception",
  "/trip/panic",
  "/trip/panic/submitted",
  "/trips",
  "/trips/active",
];

const HANDSHAKE_STEP_SLUGS: Record<number, string[]> = {
  1: ["1-approach-gate", "2-verification"],
  2: ["1-arrive-bay", "2-linehaul", "3-waybill", "4-seal", "5-review"],
  3: ["1-approach-exit", "2-exit-and-seal", "3-departure"],
  4: ["1-approach-dest", "2-seal-verify"],
  5: ["1-hand-waybill", "2-seal-break-inspection", "3-visual-count", "4-pod-photo", "5-reconciliation", "6-closed"],
};
const HANDSHAKE_ROUTES = Object.entries(HANDSHAKE_STEP_SLUGS).flatMap(([h, slugs]) =>
  slugs.map((slug) => `/trip/handshake/${h}/step/${slug}`),
);

const MOCK_TRIP_IDS = [
  "7e8f9a0b-1c2d-4e3f-8a5b-6c7d8e9f0a1b",
  "8f9a0b1c-2d3e-4f4a-8b6c-7d8e9f0a1b2c",
  "9a0b1c2d-3e4f-4a5b-8c7d-8e9f0a1b2c3d",
  "0b1c2d3e-4f5a-4b6c-8d8e-9f0a1b2c3d4e",
  "1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e5f",
  "2d3e4f5a-6b7c-4d8e-9f0a-1b2c3d4e5f6a",
  "3e4f5a6b-7c8d-4e9f-8a0b-1c2d3e4f5a6b",
];
const TRIP_DETAIL_ROUTES = MOCK_TRIP_IDS.map((id) => `/trips/${id}`);

const PRECACHED_ROUTES = [...STATIC_ROUTES, ...HANDSHAKE_ROUTES, ...TRIP_DETAIL_ROUTES];

// Each route is precached under its exact exported filename — `<route>.html` (the full
// document, needed to satisfy a hard/cold navigation) AND `<route>.txt` (the RSC flight
// payload Next's App Router client fetches for an in-app soft navigation to a route that
// hasn't been visited yet in this session). Deliberately NOT the extension-less clean URL
// (e.g. "/login"): that path only exists if the hosting layer rewrites it to the .html
// file server-side, which we can't assume here — and an entry that 404s during SW install
// fails the *entire* install (Serwist's precache fetch-and-store step isn't
// fault-tolerant per-entry). The exact exported filenames are guaranteed to exist. Where
// hosting *does* do clean-URL rewriting, an unvisited route's cold-start offline load
// falls through to the NetworkFirst navigation handler in app/sw.ts instead of an instant
// precache hit — see the comment there.
function routeToPrecacheEntries(route: string): { url: string; revision: string }[] {
  const base = route === "/" ? "/index" : route;
  return [
    { url: `${base}.html`, revision: packageJsonVersion },
    { url: `${base}.txt`, revision: packageJsonVersion },
  ];
}

// Supplying additionalPrecacheEntries below replaces @serwist/next's default public/
// scan (see note above), so public/ files it would otherwise have picked up are
// re-added explicitly here, keyed by a content hash so they only bust cache when their
// bytes actually change (relevant right now: the icon regeneration in this same change).
function publicFilePrecacheEntry(relPath: string): { url: string; revision: string } {
  const contents = fs.readFileSync(path.join(process.cwd(), "public", relPath));
  const revision = crypto.createHash("sha256").update(contents).digest("hex").slice(0, 16);
  return { url: `/${relPath}`, revision };
}

const additionalPrecacheEntries = [
  ...PRECACHED_ROUTES.flatMap(routeToPrecacheEntries),
  publicFilePrecacheEntry("manifest.json"),
  publicFilePrecacheEntry("icons/icon-192.png"),
  publicFilePrecacheEntry("icons/icon-512.png"),
];

// Disable serwist in development — the SW would intercept hot-reload requests and break fast refresh.
const withSerwist = withSerwistInit({
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  disable: process.env.NODE_ENV === "development",
  additionalPrecacheEntries,
});

export default withSerwist(nextConfig);
