"""Add the DRIVER_LOCATION_MISMATCH partial unique index (driver-location-timeline-gap).

Today DRIVER_VEHICLE_SEPARATION only fires once a real phone-to-tracker distance
was measured (`ActionLocationAssessment.proximity == "separated"`); when the
truck's Pulsit tracker fix is stale or unavailable, that comparison never runs at
all, and a driver whose phone is measurably outside the stop's precinct raises
nothing. DRIVER_LOCATION_MISMATCH (orchestration/action_location_service.
record_driver_location_finding) reads `ActionLocationAssessment.driver_in_precinct`
directly instead, so it fires independently of whether a tracker fix ever existed
to compare against.

Additive only — one new partial unique index on the existing `exceptions` table.
No new column: `exceptions.exception_type` is already `String(50)`, not a Postgres
enum, so the new ExceptionType value needs no type migration (db/models/enums.py).

Scoped to phase_event_id only, mirroring uq_exceptions_phase_separation exactly,
with no checkpoint-scoped twin: driver_in_precinct is only ever set to True/False
for a phase handshake anchored to a stop (build_phase_assessment) — a bare
checkpoint capture (build_checkpoint_assessment/build_capture_assessment) always
leaves it None, so no checkpoint index has anything to enforce.

Also declared on the SQLAlchemy model (db/models/transit.py, TripException.
__table_args__) — Base.metadata.create_all() in the test suite only picks up what
the model itself declares (see uq_exceptions_phase_separation's own precedent), so
a schema drift between "what alembic creates" and "what create_all creates" would
otherwise pass every unit test and only surface against the real database.

Hand-written, not autogenerated, matching every migration on this branch since
2026-08-26: autogenerate against the shared dev database proposes dropping
roughly a dozen live indexes and the Supabase auth FKs.

Revision ID: tim_driver_location_mismatch
Revises: 6ee6103df09a
Create Date: 2026-09-17
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "tim_driver_location_mismatch"
down_revision = "6ee6103df09a"
branch_labels = None
depends_on = None

_PHASE_DRIVER_LOCATION_INDEX = "uq_exceptions_phase_driver_location"


def upgrade() -> None:
    op.create_index(
        _PHASE_DRIVER_LOCATION_INDEX,
        "exceptions",
        ["phase_event_id", "exception_type"],
        unique=True,
        postgresql_where=sa.text(
            "exception_type = 'driver_location_mismatch' AND phase_event_id IS NOT NULL"
        ),
    )


def downgrade() -> None:
    op.drop_index(_PHASE_DRIVER_LOCATION_INDEX, table_name="exceptions")
