"""FP-281 piece A: PP manifest key on trips, hub codes on precincts, order number retired.

Adds the trip's manifest key (issuer account, origin hub, number) with an all-or-none
check and a partial unique index — one non-cancelled trip per manifest — and a hub code
per precinct, unique per principal. trips.order_number becomes nullable and loses its
live-trip unique index: nothing writes it after this revision. The column and
ix_trips_order_number are dropped later (piece C) once every branch has stopped
constructing Trip(order_number=...).

The status predicate is literal SQL, not the enum, so this revision keeps describing
the index it created whatever TripStatus becomes.

Hand-written, not autogenerated: against this project autogenerate proposes dropping
live indexes and the Supabase auth FKs (CLAUDE.md).

Revision ID: ciaran_pp_manifest_trips
Revises: ciaran_exception_claims
Create Date: 2026-10-01
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_pp_manifest_trips"
down_revision = "ciaran_exception_claims"
branch_labels = None
depends_on = None

_TRIPS = "trips"
_PRECINCTS = "precincts"
_MANIFEST_INDEX = "uq_trips_pp_manifest"
_MANIFEST_CHECK = "ck_trips_pp_manifest_all_or_none"
_LIVE_ORDER_INDEX = "uq_trips_live_order_number"
_HUB_INDEX = "uq_precincts_principal_pp_hub_code"
_MANIFEST_COLUMNS = [
    "operator_organization_id", "pp_manifest_issuer_account",
    "pp_manifest_origin_hub", "pp_manifest_number",
]
_ALL_OR_NONE = (
    "(pp_manifest_issuer_account IS NULL AND pp_manifest_origin_hub IS NULL"
    " AND pp_manifest_number IS NULL)"
    " OR (pp_manifest_issuer_account IS NOT NULL AND pp_manifest_origin_hub IS NOT NULL"
    " AND pp_manifest_number IS NOT NULL)"
)


def upgrade() -> None:
    op.add_column(_TRIPS, sa.Column("pp_manifest_issuer_account", sa.String(6), nullable=True))
    op.add_column(_TRIPS, sa.Column("pp_manifest_origin_hub", sa.String(10), nullable=True))
    op.add_column(_TRIPS, sa.Column("pp_manifest_number", sa.Integer(), nullable=True))
    op.create_check_constraint(_MANIFEST_CHECK, _TRIPS, _ALL_OR_NONE)
    op.create_index(
        _MANIFEST_INDEX, _TRIPS, _MANIFEST_COLUMNS, unique=True,
        postgresql_where=sa.text("status <> 'cancelled'"),
    )
    op.drop_index(_LIVE_ORDER_INDEX, table_name=_TRIPS)
    op.alter_column(_TRIPS, "order_number", existing_type=sa.String(100), nullable=True)

    op.add_column(_PRECINCTS, sa.Column("pp_hub_code", sa.String(10), nullable=True))
    op.create_index(
        _HUB_INDEX, _PRECINCTS, ["principal_organization_id", "pp_hub_code"], unique=True,
        postgresql_where=sa.text("pp_hub_code IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(_HUB_INDEX, table_name=_PRECINCTS)
    op.drop_column(_PRECINCTS, "pp_hub_code")

    # Trips created after upgrade have no order number. Backfill with their own
    # trip_reference (unique by constraint) so NOT NULL and the old index can return.
    op.execute("UPDATE trips SET order_number = trip_reference WHERE order_number IS NULL")
    op.alter_column(_TRIPS, "order_number", existing_type=sa.String(100), nullable=False)
    op.create_index(
        _LIVE_ORDER_INDEX, _TRIPS, ["operator_organization_id", "order_number"], unique=True,
        postgresql_where=sa.text("status IN ('created', 'active', 'exception_hold')"),
    )
    op.drop_index(_MANIFEST_INDEX, table_name=_TRIPS)
    op.drop_constraint(_MANIFEST_CHECK, _TRIPS, type_="check")
    op.drop_column(_TRIPS, "pp_manifest_number")
    op.drop_column(_TRIPS, "pp_manifest_origin_hub")
    op.drop_column(_TRIPS, "pp_manifest_issuer_account")
