"""introduce exception review semantics, migrating existing evidence

Task 1 (FP-146 follow-on). Replaces the old two-state `resolved: bool` with a
tri-state `review_status` (recorded / needs_review / reviewed) — a boolean could not
distinguish "nobody has looked at this yet" from "looked at, still needs a decision",
which is exactly the gap that let a CRITICAL exception sit unactioned indefinitely with
no way to tell it apart from a WARNING nobody had reason to open.

Existing rows are migrated, not discarded:
  - `resolved IS TRUE`            -> review_status = 'reviewed', review_outcome =
    'legacy_review' (a real outcome was never recorded for these, so this says "this was
    reviewed" without inventing a specific finding nobody made).
  - `resolved IS FALSE` + CRITICAL -> review_status = 'needs_review' (an open CRITICAL
    exception is exactly the case this migration exists to surface).
  - everything else                -> review_status = 'recorded' (the default).

The renamed contact-method column also has its stored values remapped, not just its
name: `resolution_method`'s four legacy values become `contact_method`'s three —
'phoned' -> 'phone', and 'no_contact_yet' -> NULL, because "no contact happened" belongs
on review_outcome (e.g. evidence_verified), not on a field named for the METHOD of a
contact that never happened. See ExceptionContactMethod's own comment
(db/models/enums.py) for why NO_CONTACT_YET has no equivalent in the new enum.

Hand-written, not autogenerated — matching every other migration on this branch (see
2026_08_26_ciaran_uniq_active_order_no.py): autogenerate against the shared dev
database currently proposes dropping roughly a dozen live indexes and the Supabase
auth FK linkage, none of which belongs to this change.

Revision ID: ciaran_exc_review_semantics
Revises: ciaran_exc_idempotency
Create Date: 2026-09-06
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_exc_review_semantics"
down_revision = "ciaran_exc_idempotency"
branch_labels = None
depends_on = None

_TABLE = "exceptions"


def upgrade() -> None:
    op.add_column(_TABLE, sa.Column("review_status", sa.String(20), nullable=True))
    op.add_column(_TABLE, sa.Column("review_outcome", sa.String(30), nullable=True))

    # Backfill before the NOT NULL is applied — every existing row needs a value before
    # the constraint can be enforced. CRITICAL is singled out because an unresolved
    # CRITICAL exception (a panic button, a broken seal) is the one case where "nobody
    # has looked at this yet" (recorded) understates the situation; every other severity
    # defaults to recorded, same as a freshly-raised exception would.
    op.execute("""
    UPDATE exceptions
    SET review_status = CASE
      WHEN resolved IS TRUE THEN 'reviewed'
      WHEN severity = 'critical' THEN 'needs_review'
      ELSE 'recorded'
    END,
    review_outcome = CASE WHEN resolved IS TRUE THEN 'legacy_review' ELSE NULL END
    """)
    op.alter_column(_TABLE, "review_status", nullable=False, server_default="recorded")

    op.alter_column(_TABLE, "resolved_by_user_id", new_column_name="reviewed_by_user_id")
    op.alter_column(_TABLE, "resolved_at", new_column_name="reviewed_at")
    op.alter_column(_TABLE, "resolver_note", new_column_name="review_note")
    op.alter_column(_TABLE, "resolution_method", new_column_name="contact_method")

    # Value remap on the renamed column, after the rename so both statements address it
    # by its new name. 'no_contact_yet' first: it must never be mistaken for 'phoned'
    # once relabelled, and neither UPDATE's WHERE clause overlaps the other's target.
    op.execute("UPDATE exceptions SET contact_method = NULL WHERE contact_method = 'no_contact_yet'")
    op.execute("UPDATE exceptions SET contact_method = 'phone' WHERE contact_method = 'phoned'")

    op.drop_index("ix_exceptions_trip_resolved", table_name=_TABLE)
    op.drop_column(_TABLE, "resolved")
    op.create_index(
        "ix_exceptions_trip_review_status",
        _TABLE, ["trip_id", "review_status"], unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_exceptions_trip_review_status", table_name=_TABLE)

    op.add_column(_TABLE, sa.Column("resolved", sa.Boolean(), nullable=True))
    op.execute("UPDATE exceptions SET resolved = (review_status = 'reviewed')")
    op.alter_column(_TABLE, "resolved", nullable=False, server_default="false")
    op.create_index("ix_exceptions_trip_resolved", _TABLE, ["trip_id", "resolved"])

    # 'no_contact_yet' has no way back — the upgrade folded it into NULL alongside every
    # row that simply never had a method recorded, and the two are now indistinguishable.
    # Only the reversible half of the remap (phone -> phoned) is undone.
    op.execute("UPDATE exceptions SET contact_method = 'phoned' WHERE contact_method = 'phone'")
    op.alter_column(_TABLE, "contact_method", new_column_name="resolution_method")
    op.alter_column(_TABLE, "review_note", new_column_name="resolver_note")
    op.alter_column(_TABLE, "reviewed_at", new_column_name="resolved_at")
    op.alter_column(_TABLE, "reviewed_by_user_id", new_column_name="resolved_by_user_id")

    op.drop_column(_TABLE, "review_outcome")
    op.drop_column(_TABLE, "review_status")
