"""FP-153 analytics read models: five materialized views over the evidence ledger

Revision ID: tom_analytics_read_models
Revises: chiko_receipt_hash_index
Create Date: 2026-09-10

Hand-written, not autogenerated: autogenerate compares Base.metadata against tables
and has no notion of a materialized view, so it could never emit this DDL.

Every view reads only `trips`, `phase_events`, `exceptions` and `trip_stops`, and every
statement below is plain SQL kept in this file rather than imported from `app/` — a
migration is a frozen record of what was applied, and must not change meaning when
application code later moves on. tests/integration/test_analytics.py loads
UPGRADE_STATEMENTS from this module directly, so the SQL under test is the SQL shipped.

Design decisions (full rationale: docs/design-notes/2026-09-10-fp153-analytics-read-models-spec.md):
  * Only CLOSED trips are counted — an open trip's numbers are not final yet.
  * A trip's departure is read from the phase LEDGER (earliest attested departure
    phase), never from trips.actual_departure_at: that cache is overwritten on every
    leg of a multi-stop trip, so it holds the LAST departure, not the first.
  * Overridden phases are excluded from every timing and corroboration measure: their
    completed_at is the dispatcher's click, and override never runs corroboration, so
    they carry no real evidence of when or where anything happened.
  * Months are calendar months in South African time, matching the operating day
    OPERATIONS_UTC_OFFSET_HOURS already defines for the rest of the app.
  * Every grain is keyed by operator_organization_id: precincts can be shared between
    operators, and one operator must never see another's trips in a lane or facility row.
  * Rates are stored as numerator/denominator (and averages as sum/count) so a range
    query can sum months first and divide once.
"""

from alembic import op

revision = "tom_analytics_read_models"
down_revision = "chiko_receipt_hash_index"
branch_labels = None
depends_on = None

# SAST is permanently UTC+2 with no daylight saving; the named zone is used so the
# boundary reads as intent in the SQL rather than as a bare offset.
_OPERATIONS_TIME_ZONE = "Africa/Johannesburg"

# Phase statuses that mean "the driver actually did this, at completed_at".
# EXCEPTION is a completion that also recorded an anomaly; OVERRIDDEN is excluded
# on purpose (see module docstring). Mirrored by ATTESTED_PHASE_STATUSES in
# app/analytics/views.py for the one live query that reads base tables.
_ATTESTED_STATUSES = "('completed', 'exception')"

_DWELL_PHASES: tuple[str, ...] = ("activation", "loading", "departure", "unloading", "confirmation")

# ── Shared CTE fragments ─────────────────────────────────────────────────────
# Every view starts from the same definition of "a closed trip and its month", so it is
# written once here and spliced into each view rather than drifting across five copies.

_CLOSED_TRIPS_CTE = f"""
trip_departures AS (
    SELECT pe.trip_id, MIN(pe.completed_at) AS departed_at
    FROM phase_events pe
    WHERE pe.phase_type = 'departure'
      AND pe.status IN {_ATTESTED_STATUSES}
      AND pe.completed_at IS NOT NULL
    GROUP BY pe.trip_id
),
closed_trips AS (
    SELECT
        t.id AS trip_id,
        t.operator_organization_id,
        t.driver_id,
        t.horse_id,
        t.origin_precinct_id,
        t.destination_precinct_id,
        t.planned_departure_at,
        t.planned_arrival_at,
        t.actual_arrival_at,
        d.departed_at,
        date_trunc('month', d.departed_at AT TIME ZONE '{_OPERATIONS_TIME_ZONE}')::date AS month_start
    FROM trips t
    JOIN trip_departures d ON d.trip_id = t.id
    WHERE t.status = 'closed'
)"""

_TRIP_EXCEPTIONS_CTE = """
trip_exceptions AS (
    SELECT
        e.trip_id,
        COUNT(*)::integer AS total_count,
        (COUNT(*) FILTER (WHERE e.severity = 'info'))::integer AS info_count,
        (COUNT(*) FILTER (WHERE e.severity = 'warning'))::integer AS warning_count,
        (COUNT(*) FILTER (WHERE e.severity = 'critical'))::integer AS critical_count
    FROM exceptions e
    JOIN closed_trips ct ON ct.trip_id = e.trip_id
    GROUP BY e.trip_id
)"""

# Each phase row alongside the phase immediately before it in the trip's committed
# plan. The window runs over EVERY row of the trip (trip_creation included), so the
# predecessor is always the true previous plan step; filters are applied afterwards.
_TRIP_PHASES_CTE = """
trip_phases AS (
    SELECT
        ct.operator_organization_id,
        ct.driver_id,
        ct.horse_id,
        ct.month_start,
        pe.phase_type,
        pe.status,
        pe.dispatcher_override_user_id,
        pe.completed_at,
        LAG(pe.phase_type) OVER plan_order AS prev_phase_type,
        LAG(pe.status) OVER plan_order AS prev_status,
        LAG(pe.completed_at) OVER plan_order AS prev_completed_at
    FROM phase_events pe
    JOIN closed_trips ct ON ct.trip_id = pe.trip_id
    WINDOW plan_order AS (PARTITION BY pe.trip_id ORDER BY pe.sequence_number)
)"""

# A gap between two phases is only a real measurement when BOTH ends were attested.
_GAP_IS_ATTESTED = (
    f"status IN {_ATTESTED_STATUSES} AND prev_status IN {_ATTESTED_STATUSES} "
    "AND completed_at IS NOT NULL AND prev_completed_at IS NOT NULL"
)
_GAP_MINUTES = "EXTRACT(EPOCH FROM (completed_at - prev_completed_at))::double precision / 60.0"
_GAP_HOURS = "EXTRACT(EPOCH FROM (completed_at - prev_completed_at))::double precision / 3600.0"


def _dwell_columns() -> str:
    """One sum/count pair per measured phase — generated because the five are identical
    in shape and differ only in the phase name."""
    columns: list[str] = []
    for phase in _DWELL_PHASES:
        observed = f"phase_type = '{phase}' AND {_GAP_IS_ATTESTED}"
        columns.append(
            f"COALESCE(SUM({_GAP_MINUTES}) FILTER (WHERE {observed}), 0)::double precision "
            f"AS {phase}_dwell_minutes_sum"
        )
        columns.append(f"(COUNT(*) FILTER (WHERE {observed}))::integer AS {phase}_dwell_events_count")
    return ",\n        ".join(columns)


def _dwell_select() -> str:
    return ",\n    ".join(
        f"pt.{phase}_dwell_minutes_sum, pt.{phase}_dwell_events_count" for phase in _DWELL_PHASES
    )


# ── Driver ───────────────────────────────────────────────────────────────────

_DRIVER_ANALYTICS = f"""
CREATE MATERIALIZED VIEW driver_analytics AS
WITH {_CLOSED_TRIPS_CTE},
{_TRIP_EXCEPTIONS_CTE},
{_TRIP_PHASES_CTE},
trip_totals AS (
    SELECT
        ct.operator_organization_id,
        ct.driver_id,
        ct.month_start,
        COUNT(*)::integer AS trip_count,
        COUNT(te.trip_id)::integer AS trips_with_exceptions_count,
        COALESCE(SUM(te.total_count), 0)::integer AS total_exceptions_count,
        COALESCE(SUM(te.info_count), 0)::integer AS info_exceptions_count,
        COALESCE(SUM(te.warning_count), 0)::integer AS warning_exceptions_count,
        COALESCE(SUM(te.critical_count), 0)::integer AS critical_exceptions_count,
        (COUNT(*) FILTER (WHERE ct.planned_departure_at IS NOT NULL))::integer AS departures_with_plan_count,
        -- Strict: no grace window is defined anywhere in the codebase or the docs.
        (COUNT(*) FILTER (WHERE ct.departed_at <= ct.planned_departure_at))::integer AS on_time_departures_count
    FROM closed_trips ct
    LEFT JOIN trip_exceptions te ON te.trip_id = ct.trip_id
    GROUP BY ct.operator_organization_id, ct.driver_id, ct.month_start
),
phase_totals AS (
    SELECT
        operator_organization_id,
        driver_id,
        month_start,
        COUNT(*)::integer AS phase_events_count,
        (COUNT(*) FILTER (WHERE dispatcher_override_user_id IS NOT NULL))::integer AS override_count,
        {_dwell_columns()}
    FROM trip_phases
    GROUP BY operator_organization_id, driver_id, month_start
)
SELECT
    tt.operator_organization_id,
    tt.driver_id,
    tt.month_start,
    tt.trip_count,
    tt.trips_with_exceptions_count,
    tt.total_exceptions_count,
    tt.info_exceptions_count,
    tt.warning_exceptions_count,
    tt.critical_exceptions_count,
    tt.departures_with_plan_count,
    tt.on_time_departures_count,
    {_dwell_select()},
    pt.phase_events_count,
    pt.override_count
FROM trip_totals tt
JOIN phase_totals pt
  ON pt.operator_organization_id = tt.operator_organization_id
 AND pt.driver_id = tt.driver_id
 AND pt.month_start = tt.month_start
"""

# ── Vehicle (monthly) ────────────────────────────────────────────────────────

_VEHICLE_ANALYTICS = f"""
CREATE MATERIALIZED VIEW vehicle_analytics AS
WITH {_CLOSED_TRIPS_CTE},
{_TRIP_PHASES_CTE},
mechanical AS (
    -- The window sees the vehicle's whole closed-trip history, so each breakdown's gap
    -- is measured from the previous breakdown even when that one fell in an earlier
    -- month. The first-ever breakdown has no predecessor and therefore no gap.
    SELECT
        ct.operator_organization_id,
        ct.horse_id,
        ct.month_start,
        e.severity,
        e.created_at - LAG(e.created_at) OVER (
            PARTITION BY ct.operator_organization_id, ct.horse_id
            ORDER BY e.created_at, e.id
        ) AS gap
    FROM exceptions e
    JOIN closed_trips ct ON ct.trip_id = e.trip_id
    WHERE e.exception_type = 'mechanical'
),
trip_totals AS (
    SELECT operator_organization_id, horse_id, month_start, COUNT(*)::integer AS trip_count
    FROM closed_trips
    GROUP BY operator_organization_id, horse_id, month_start
),
mechanical_totals AS (
    SELECT
        operator_organization_id,
        horse_id,
        month_start,
        COUNT(*)::integer AS mechanical_exceptions_count,
        (COUNT(*) FILTER (WHERE severity = 'info'))::integer AS mechanical_info_count,
        (COUNT(*) FILTER (WHERE severity = 'warning'))::integer AS mechanical_warning_count,
        (COUNT(*) FILTER (WHERE severity = 'critical'))::integer AS mechanical_critical_count,
        COALESCE(SUM(EXTRACT(EPOCH FROM gap)::double precision / 60.0), 0)::double precision
            AS mechanical_gap_minutes_sum,
        COUNT(gap)::integer AS mechanical_gap_count
    FROM mechanical
    GROUP BY operator_organization_id, horse_id, month_start
),
driving_totals AS (
    -- In-transit legs only (departure -> arrival): road time, for wear and maintenance,
    -- deliberately not door-to-door duration.
    SELECT operator_organization_id, horse_id, month_start, SUM({_GAP_HOURS}) AS driving_hours_sum
    FROM trip_phases
    WHERE phase_type = 'in_transit' AND prev_phase_type = 'departure' AND {_GAP_IS_ATTESTED}
    GROUP BY operator_organization_id, horse_id, month_start
)
SELECT
    tt.operator_organization_id,
    tt.horse_id AS vehicle_id,
    tt.month_start,
    tt.trip_count,
    COALESCE(mt.mechanical_exceptions_count, 0) AS mechanical_exceptions_count,
    COALESCE(mt.mechanical_info_count, 0) AS mechanical_info_count,
    COALESCE(mt.mechanical_warning_count, 0) AS mechanical_warning_count,
    COALESCE(mt.mechanical_critical_count, 0) AS mechanical_critical_count,
    COALESCE(mt.mechanical_gap_minutes_sum, 0)::double precision AS mechanical_gap_minutes_sum,
    COALESCE(mt.mechanical_gap_count, 0) AS mechanical_gap_count,
    COALESCE(dt.driving_hours_sum, 0)::double precision AS driving_hours_sum
FROM trip_totals tt
LEFT JOIN mechanical_totals mt
  ON mt.operator_organization_id = tt.operator_organization_id
 AND mt.horse_id = tt.horse_id
 AND mt.month_start = tt.month_start
LEFT JOIN driving_totals dt
  ON dt.operator_organization_id = tt.operator_organization_id
 AND dt.horse_id = tt.horse_id
 AND dt.month_start = tt.month_start
"""

# ── Vehicle incident streaks (whole history, one row per vehicle) ────────────
# An incident is a closed trip carrying at least one MECHANICAL exception — two reports
# on the same trip are one incident, not a zero-trip streak between them. Streaks are
# counted in clean trips, never days: an idle truck proves nothing about reliability.

_VEHICLE_INCIDENT_STREAKS = f"""
CREATE MATERIALIZED VIEW vehicle_incident_streaks AS
WITH {_CLOSED_TRIPS_CTE},
trip_incidents AS (
    SELECT
        ct.operator_organization_id,
        ct.horse_id,
        ct.trip_id,
        ct.departed_at,
        EXISTS (
            SELECT 1 FROM exceptions e
            WHERE e.trip_id = ct.trip_id AND e.exception_type = 'mechanical'
        ) AS is_incident
    FROM closed_trips ct
),
positioned AS (
    -- segment = how many incidents came before this trip. Clean trips sharing a
    -- segment number form one streak; segment 0 is the run before the first incident.
    SELECT
        operator_organization_id,
        horse_id,
        is_incident,
        (COUNT(*) FILTER (WHERE is_incident) OVER (
            PARTITION BY operator_organization_id, horse_id
            ORDER BY departed_at, trip_id
            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ))::integer AS segment
    FROM trip_incidents
),
incident_totals AS (
    SELECT operator_organization_id, horse_id, (COUNT(*) FILTER (WHERE is_incident))::integer AS incident_count
    FROM trip_incidents
    GROUP BY operator_organization_id, horse_id
),
segments AS (
    -- Enumerated explicitly so a segment with ZERO clean trips (back-to-back incident
    -- trips) still exists and can be the lowest streak, instead of vanishing from a GROUP BY.
    SELECT it.operator_organization_id, it.horse_id, it.incident_count, s.segment
    FROM incident_totals it
    CROSS JOIN LATERAL generate_series(0, it.incident_count) AS s(segment)
),
segment_lengths AS (
    SELECT
        s.operator_organization_id,
        s.horse_id,
        s.incident_count,
        s.segment,
        COUNT(p.horse_id)::integer AS clean_trips
    FROM segments s
    LEFT JOIN positioned p
      ON p.operator_organization_id = s.operator_organization_id
     AND p.horse_id = s.horse_id
     AND p.segment = s.segment
     AND NOT p.is_incident
    GROUP BY s.operator_organization_id, s.horse_id, s.incident_count, s.segment
)
SELECT
    operator_organization_id,
    horse_id AS vehicle_id,
    -- The open segment (segment = incident_count) counts: if it already beats every
    -- completed run it is already the record.
    MAX(clean_trips)::integer AS highest_streak_trips,
    -- Completed segments only: the open one can still grow. NULL when no incident has
    -- ever closed a segment.
    (MIN(clean_trips) FILTER (WHERE segment < incident_count))::integer AS lowest_streak_trips
FROM segment_lengths
GROUP BY operator_organization_id, horse_id
"""

# ── Lane ─────────────────────────────────────────────────────────────────────
# Arrays, not sum/count: median and P90 cannot be recombined from per-month values, only
# recomputed over the pooled raw observations. Each schedule delta is computed per trip
# here, so it can never be paired with the wrong trip's plan later.

_ACTUAL_MINUTES = "EXTRACT(EPOCH FROM (ct.actual_arrival_at - ct.departed_at))::double precision / 60.0"
_PLANNED_MINUTES = (
    "EXTRACT(EPOCH FROM (ct.planned_arrival_at - ct.planned_departure_at))::double precision / 60.0"
)

_LANE_ANALYTICS = f"""
CREATE MATERIALIZED VIEW lane_analytics AS
WITH {_CLOSED_TRIPS_CTE},
{_TRIP_EXCEPTIONS_CTE}
SELECT
    ct.operator_organization_id,
    ct.origin_precinct_id,
    ct.destination_precinct_id,
    ct.month_start,
    COUNT(*)::integer AS trip_count,
    COALESCE(SUM(te.total_count), 0)::integer AS exception_count,
    COALESCE(
        array_agg({_ACTUAL_MINUTES} ORDER BY ct.trip_id)
            FILTER (WHERE ct.actual_arrival_at IS NOT NULL),
        ARRAY[]::double precision[]
    ) AS actual_transit_minutes,
    COALESCE(
        array_agg(({_ACTUAL_MINUTES}) - ({_PLANNED_MINUTES}) ORDER BY ct.trip_id)
            FILTER (
                WHERE ct.actual_arrival_at IS NOT NULL
                  AND ct.planned_departure_at IS NOT NULL
                  AND ct.planned_arrival_at IS NOT NULL
            ),
        ARRAY[]::double precision[]
    ) AS schedule_delta_minutes
FROM closed_trips ct
LEFT JOIN trip_exceptions te ON te.trip_id = ct.trip_id
-- A trip with an unknown endpoint is not on any lane.
WHERE ct.origin_precinct_id IS NOT NULL AND ct.destination_precinct_id IS NOT NULL
GROUP BY ct.operator_organization_id, ct.origin_precinct_id, ct.destination_precinct_id, ct.month_start
"""

# ── Facility ─────────────────────────────────────────────────────────────────
# in_transit is excluded: corroboration_service deliberately never gives it a verdict
# (it is anchored to the stop it DEPARTED from), so it would read NULL forever and
# pollute unwitnessed_count with rows that were never going to be checked. The same
# holds for overridden rows, which never run corroboration at all. trip_creation has no
# stop and drops out of the inner join on its own.

_FACILITY_ANALYTICS = f"""
CREATE MATERIALIZED VIEW facility_analytics AS
WITH {_CLOSED_TRIPS_CTE}
SELECT
    ct.operator_organization_id,
    ts.precinct_id,
    ct.month_start,
    (COUNT(*) FILTER (WHERE pe.pulsit_geofence_confirmed IS TRUE))::integer AS confirmed_count,
    (COUNT(*) FILTER (WHERE pe.pulsit_geofence_confirmed IS FALSE))::integer AS mismatch_count,
    (COUNT(*) FILTER (WHERE pe.pulsit_geofence_confirmed IS NULL))::integer AS unwitnessed_count
FROM phase_events pe
JOIN closed_trips ct ON ct.trip_id = pe.trip_id
JOIN trip_stops ts ON ts.id = pe.trip_stop_id
WHERE pe.phase_type <> 'in_transit'
  AND pe.status IN {_ATTESTED_STATUSES}
GROUP BY ct.operator_organization_id, ts.precinct_id, ct.month_start
"""

# ── Unique indexes ───────────────────────────────────────────────────────────
# REFRESH MATERIALIZED VIEW CONCURRENTLY refuses to run without a unique index over
# plain columns covering every row — one per view, on exactly its grain.

_VIEW_GRAINS: dict[str, tuple[str, ...]] = {
    "driver_analytics": ("operator_organization_id", "driver_id", "month_start"),
    "vehicle_analytics": ("operator_organization_id", "vehicle_id", "month_start"),
    "vehicle_incident_streaks": ("operator_organization_id", "vehicle_id"),
    "lane_analytics": (
        "operator_organization_id", "origin_precinct_id", "destination_precinct_id", "month_start",
    ),
    "facility_analytics": ("operator_organization_id", "precinct_id", "month_start"),
}

_UNIQUE_INDEXES: tuple[str, ...] = tuple(
    f"CREATE UNIQUE INDEX uq_{view}_grain ON {view} ({', '.join(columns)})"
    for view, columns in _VIEW_GRAINS.items()
)

# ── Data API lockdown ────────────────────────────────────────────────────────
# 0003_tom_rls_policies closed PostgREST off from every table with RLS, but RLS cannot
# be enabled on a materialized view, and Supabase's default privileges grant new public
# objects to anon/authenticated. Without this REVOKE, every operator's analytics would
# be readable cross-tenant through the Data API. Guarded on the roles existing so the
# statement is a no-op on a plain Postgres (the test database, a local instance).
_REVOKE_DATA_API_ACCESS = f"""
DO $$
DECLARE
    api_role text;
BEGIN
    FOREACH api_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('REVOKE ALL ON {", ".join(_VIEW_GRAINS)} FROM %I', api_role);
        END IF;
    END LOOP;
END $$
"""

UPGRADE_STATEMENTS: tuple[str, ...] = (
    _DRIVER_ANALYTICS,
    _VEHICLE_ANALYTICS,
    _VEHICLE_INCIDENT_STREAKS,
    _LANE_ANALYTICS,
    _FACILITY_ANALYTICS,
    *_UNIQUE_INDEXES,
    _REVOKE_DATA_API_ACCESS,
)

DOWNGRADE_STATEMENTS: tuple[str, ...] = tuple(
    f"DROP MATERIALIZED VIEW IF EXISTS {view}" for view in reversed(tuple(_VIEW_GRAINS))
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    # Unique indexes are owned by their views and go with them.
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
