"""add exceptions.resolution_method

Records HOW a dispatcher established what happened before resolving an exception —
phoned, whatsapp, in_person, or no_contact_yet. The other four resolution columns
(resolved, resolved_by_user_id, resolved_at, resolver_note) already exist; only the
method was missing.

Hand-written, not autogenerated. `alembic revision --autogenerate` against this
codebase on 2026-09-03 additionally proposed dropping 17 indexes (trips, parcels,
exceptions, blockchain_receipts, checkpoints, driver_events, vehicles, …) and the
fk_users_auth_id / fk_drivers_auth_id constraints into Supabase's `auth` schema. That
drift is pre-existing — those objects are created by earlier migrations but not
declared on the models, so autogenerate reads them as removals. None of it belongs to
this change, and shipping it would have taken out the project's indexes and its auth
linkage. If you regenerate this file, scope it back to the single column by hand.

String(20), not a native PG enum: matches exception_type / source / severity on the
same table and every other enum column in this codebase, and needs no CREATE/DROP TYPE.

Revision ID: ciaran_exc_resolution_method
Revises: ciaran_precinct_events
Create Date: 2026-09-03
"""
from alembic import op
import sqlalchemy as sa

revision = "ciaran_exc_resolution_method"
down_revision = "ciaran_precinct_events"
branch_labels = None
depends_on = None

_TABLE = "exceptions"
_COLUMN = "resolution_method"


def upgrade() -> None:
    # Nullable with no server_default and no backfill: every exception resolved before
    # this column existed genuinely has no recorded method, and stamping one on would
    # write invented contact history onto an evidence record.
    op.add_column(_TABLE, sa.Column(_COLUMN, sa.String(length=20), nullable=True))


def downgrade() -> None:
    op.drop_column(_TABLE, _COLUMN)
