"""Add a geofence verdict per trailer snapshot, and TRAILER_LOCATION_MISMATCH's index.

Until now only the horse got a geofence verdict at each stop phase
(phase_events.pulsit_geofence_confirmed). Trailers got a position snapshot and nothing
else, so a trailer left behind somewhere while its horse drove on to the gate was never
judged. trailer_gps_snapshots.geofence_confirmed closes that, with the same three-state
meaning as the horse's column: TRUE inside, FALSE measured outside, NULL could not
check.

The partial unique index is the idempotency key for the new TRAILER_LOCATION_MISMATCH
exception (one per phase event), the same pattern as uq_exceptions_phase_separation and
uq_exceptions_phase_driver_location. Also declared on TripException.__table_args__ so the
test suite's create_all builds it too. exceptions.exception_type is String(50), so the new
ExceptionType value itself needs no migration.

Additive only. Hand-written, not autogenerated: against this project autogenerate
proposes dropping live indexes and the Supabase auth FKs.

Revision ID: ciaran_trailer_geofence
Revises: ciaran_arrival_seal_condition
Create Date: 2026-09-23
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_trailer_geofence"
down_revision = "ciaran_arrival_seal_condition"
branch_labels = None
depends_on = None

_TRAILER_LOCATION_INDEX = "uq_exceptions_phase_trailer_location"


def upgrade() -> None:
    op.add_column(
        "trailer_gps_snapshots",
        sa.Column("geofence_confirmed", sa.Boolean(), nullable=True),
    )
    op.create_index(
        _TRAILER_LOCATION_INDEX,
        "exceptions",
        ["phase_event_id", "exception_type"],
        unique=True,
        postgresql_where=sa.text(
            "exception_type = 'trailer_location_mismatch' AND phase_event_id IS NOT NULL"
        ),
    )


def downgrade() -> None:
    op.drop_index(_TRAILER_LOCATION_INDEX, table_name="exceptions")
    op.drop_column("trailer_gps_snapshots", "geofence_confirmed")
