"""Add audit_packs, audit_pack_access_events and incident_declarations (insurer audit trail).

An audit pack is a frozen manifest of one trip (or one consignment on it), rendered to a
PDF that is stored, hashed and sealed on Hedera, and shared through an expiring,
revocable link. See docs/design-notes/2026-09-23-insurer-audit-trail-plan.md §9.1.

incident_declarations holds the claim-form facts FreightProof cannot capture itself
(SAPS station and CAS number, who was notified when), append-only, shown in packs under
the Declared tier.

Additive only — three new tables, no change to any existing one. The new enum values
(SubjectType.AUDIT_PACK, BlockchainReceiptType.AUDIT_PACK_ISSUED,
AuditPackAccessEventType) live in String columns, so they need no type migration.

Hand-written, not autogenerated: autogenerate against the shared dev database proposes
dropping ~21 live indexes and the Supabase auth FKs
(docs/design-notes/2026-09-15-alembic-autogenerate-drift.md).

Revision ID: tim_add_audit_packs
Revises: tim_driver_location_mismatch
Create Date: 2026-09-23
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "tim_add_audit_packs"
down_revision = "tim_driver_location_mismatch"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "audit_packs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("consignment_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("pack_version", sa.SmallInteger(), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("external_reference", sa.String(length=100), nullable=True),
        sa.Column("recipient_name", sa.String(length=200), nullable=False),
        sa.Column("recipient_organization", sa.String(length=200), nullable=False),
        sa.Column("recipient_email", sa.String(length=320), nullable=True),
        sa.Column("include_location_trail", sa.Boolean(), nullable=False),
        sa.Column("include_full_driver_id", sa.Boolean(), nullable=False),
        sa.Column("manifest_version", sa.SmallInteger(), nullable=False),
        sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("pdf_storage_bucket", sa.String(length=255), nullable=False),
        sa.Column("pdf_storage_key", sa.String(length=500), nullable=False),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=False),
        sa.Column("pdf_size_bytes", sa.Integer(), nullable=False),
        sa.Column("anchor_status", sa.String(length=20), nullable=False),
        sa.Column("blockchain_receipt_id", sa.UUID(), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by_user_id", sa.UUID(), nullable=False),
        sa.Column("revoked_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], name="fk_audit_packs_trip_id"),
        sa.ForeignKeyConstraint(["consignment_id"], ["consignments.id"], name="fk_audit_packs_consignment_id"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], name="fk_audit_packs_organization_id"),
        sa.ForeignKeyConstraint(
            ["blockchain_receipt_id"], ["blockchain_receipts.id"], name="fk_audit_packs_blockchain_receipt_id",
        ),
        sa.ForeignKeyConstraint(["issued_by_user_id"], ["users.id"], name="fk_audit_packs_issued_by_user_id"),
        sa.ForeignKeyConstraint(["revoked_by_user_id"], ["users.id"], name="fk_audit_packs_revoked_by_user_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "pack_version", name="uq_audit_packs_trip_version"),
    )
    op.create_index("uq_audit_packs_token_hash", "audit_packs", ["token_hash"], unique=True)
    op.create_index("ix_audit_packs_trip_id", "audit_packs", ["trip_id"])

    op.create_table(
        "audit_pack_access_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_pack_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_pack_id"], ["audit_packs.id"], name="fk_audit_pack_access_events_audit_pack_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_pack_access_events_pack_created", "audit_pack_access_events", ["audit_pack_id", "created_at"],
    )

    op.create_table(
        "incident_declarations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("exception_id", sa.UUID(), nullable=True),
        sa.Column("saps_station", sa.String(length=200), nullable=True),
        sa.Column("saps_cas_number", sa.String(length=50), nullable=True),
        sa.Column("saps_officer", sa.String(length=200), nullable=True),
        sa.Column("reported_to_saps_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tracking_company_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("insurer_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("insurer_claim_reference", sa.String(length=100), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("declared_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], name="fk_incident_declarations_trip_id"),
        sa.ForeignKeyConstraint(["exception_id"], ["exceptions.id"], name="fk_incident_declarations_exception_id"),
        sa.ForeignKeyConstraint(
            ["declared_by_user_id"], ["users.id"], name="fk_incident_declarations_declared_by_user_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incident_declarations_trip_created", "incident_declarations", ["trip_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_incident_declarations_trip_created", table_name="incident_declarations")
    op.drop_table("incident_declarations")
    op.drop_index("ix_audit_pack_access_events_pack_created", table_name="audit_pack_access_events")
    op.drop_table("audit_pack_access_events")
    op.drop_index("ix_audit_packs_trip_id", table_name="audit_packs")
    op.drop_index("uq_audit_packs_token_hash", table_name="audit_packs")
    op.drop_table("audit_packs")
