"""one live trip per order number — partial unique index on trips

trip_service._check_order_number_conflict already refuses a duplicate order number,
but a check and an insert are two statements. Two dispatchers submitting the same
customer order at the same moment both clear that check before either has inserted,
and both get a trip. Each then anchors its own journey-lock hash, so one order
acquires two contradictory records on an append-only ledger.

Partial rather than total, and that is the whole design: a closed or cancelled order
number is legitimately reusable, so only live rows take part in the uniqueness. The
predicate mirrors LIVE_TRIP_STATUSES in db/models/trips.py, which orchestration reads
for the application-side check — the two must agree on what "live" means.

The status values are written out as literal SQL rather than imported from the enum
on purpose. A migration is a historical snapshot: if TripStatus gains or loses a
member later, this revision must keep describing the index it actually created, not
whatever the enum has become by then.

Hand-written, not autogenerated: `alembic revision --autogenerate` against the shared
dev database currently reports a large baseline drift and would have proposed dropping
roughly a dozen live indexes alongside this one.

Verified before writing: the dev database held 22 trips and zero duplicate
(operator_organization_id, order_number) pairs among live statuses, so this applies
with no data migration. Re-check before applying elsewhere — upgrade() fails loudly
on pre-existing duplicates rather than deleting anything, which is correct: which of
two trips owns a customer order is an operational decision, not a migration's.

Revision ID: ciaran_uniq_order_no
Revises: ciaran_uniq_waybill_ref
Create Date: 2026-08-26
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters: alembic_version.version_num is varchar(32),
# and a longer id lets the DDL succeed and then fails on the version bump, rolling
# the whole migration back with a confusing error.
revision = "ciaran_uniq_order_no"
down_revision = "ciaran_uniq_waybill_ref"
branch_labels = None
depends_on = None

_INDEX_NAME = "uq_trips_live_order_number"
_LIVE_STATUSES = "status IN ('created', 'active', 'exception_hold')"


def upgrade() -> None:
    op.create_index(
        _INDEX_NAME,
        "trips",
        ["operator_organization_id", "order_number"],
        unique=True,
        postgresql_where=sa.text(_LIVE_STATUSES),
    )


def downgrade() -> None:
    op.drop_index(_INDEX_NAME, table_name="trips")
