"""Add phase_events.seal_condition for the Arrival phase.

Arrival records the seal as found at the destination gate, before anything is opened:
its number, a photo, and its physical condition (intact / damaged / missing). The number
and photo reuse the existing per-row seal_number and seal_photo_artifact_id columns, so
the condition is the only new fact. See
docs/design-notes/2026-09-23-arrival-phase-and-live-journey.md §4.2.

Additive only - one nullable column. Plain String, not a Postgres enum, like every enum
column on this table, so a new SealCondition value never needs a type migration. NULL on
every phase type except arrival. PhaseType.ARRIVAL itself needs no migration either:
phase_events.phase_type is String(30).

phase_events.gate_photo_artifact_id is now unused (the arrival seal photo replaced it). It
is deliberately NOT dropped here: removing a column and changing behaviour in the same
migration is the risky combination on a shared database. A later migration drops it.

Hand-written, not autogenerated: against this project autogenerate proposes dropping
live indexes and the Supabase auth FKs.

Revision ID: ciaran_arrival_seal_condition
Revises: ciaran_lock_down_data_api
Create Date: 2026-09-23
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_arrival_seal_condition"
down_revision = "ciaran_lock_down_data_api"
branch_labels = None
depends_on = None

# Mirrors PhaseEvent.seal_condition in app/db/models/phases.py.
_SEAL_CONDITION_LENGTH = 20


def upgrade() -> None:
    op.add_column(
        "phase_events",
        sa.Column("seal_condition", sa.String(_SEAL_CONDITION_LENGTH), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("phase_events", "seal_condition")
