"""Storage for ActionLocationAssessment snapshots + the driver_vehicle_separation
exception type (Task 5 of the trip-location-timeline-improvements story).

Additive only, no backfill and no data migration — every column here is nullable
and every existing row simply reads NULL/absent for it, exactly like every other
evidence-snapshot column this codebase has added (driver_captured_at, client_report_id).

What this migration is for, and what it deliberately is NOT for yet:

  * `phase_events.action_location_assessment` / `checkpoints.action_location_
    assessment` / `exceptions.action_location_assessment` — the JSONB snapshot of
    one ActionLocationAssessment (schemas/action_location.py, Task 4), assembled by
    Task 5's orchestration/action_location_service.py and validated through that
    model on every read. Never arbitrary dict storage at the API boundary.

  * `phase_events.location_warning_acknowledged_at` / `location_warning_reason` —
    column only. Task 7 owns the acknowledgement workflow that writes to these; no
    logic in this story reads or writes them yet.

  * `checkpoints.client_report_id` / `checkpoints.phase_event_id` (+ the partial
    unique index on client_report_id) — column/index only, mirroring exactly what
    `exceptions.client_report_id` already does (migration ciaran_exc_idempotency).
    Task 8 wires these through checkpoint_service.log_checkpoint; this story's own
    checkpoint path does not touch them.

  * Two narrow partial unique indexes scoped to the NEW exception_type only —
    `(phase_event_id, exception_type) WHERE exception_type = 'driver_vehicle_
    separation' AND phase_event_id IS NOT NULL` and the checkpoint-scoped twin.
    They give orchestration/action_location_service.record_separation_finding an
    idempotency key for exactly one row per source event, the same pattern
    uq_exceptions_trip_client_report_id already established, without touching
    uniqueness for GPS_MISMATCH or any other exception type on this table.

Every column/index here is also declared on the SQLAlchemy models (db/models/
phases.py, db/models/transit.py) — Base.metadata.create_all() in the test suite
only picks up what the model itself declares (see uq_exceptions_trip_client_
report_id's own precedent), so a schema drift between "what alembic creates" and
"what create_all creates" would otherwise pass every unit test and only surface
against the real database.

Hand-written, not autogenerated, matching every migration on this branch since
2026-08-26: autogenerate against the shared dev database proposes dropping roughly
a dozen live indexes and the Supabase auth FKs.

Revision ID: ciaran_action_location
Revises: tom_live_analytics_views
Create Date: 2026-09-15
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_action_location"
down_revision = "tom_live_analytics_views"
branch_labels = None
depends_on = None

_ASSESSMENT_COLUMN = "action_location_assessment"

_CHECKPOINT_REPORT_ID_INDEX = "uq_checkpoints_trip_client_report_id"

_PHASE_SEPARATION_INDEX = "uq_exceptions_phase_separation"
_CHECKPOINT_SEPARATION_INDEX = "uq_exceptions_checkpoint_separation"


def upgrade() -> None:
    # ── phase_events ─────────────────────────────────────────────────────────
    op.add_column("phase_events", sa.Column(_ASSESSMENT_COLUMN, JSONB, nullable=True))
    # Task 7 columns — no reader/writer in this story, see module docstring.
    op.add_column(
        "phase_events",
        sa.Column("location_warning_acknowledged_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("phase_events", sa.Column("location_warning_reason", sa.Text(), nullable=True))

    # ── checkpoints ──────────────────────────────────────────────────────────
    op.add_column("checkpoints", sa.Column(_ASSESSMENT_COLUMN, JSONB, nullable=True))
    # Task 8 columns — mirrors exceptions.client_report_id exactly (migration
    # ciaran_exc_idempotency); no caller in this story populates either.
    op.add_column(
        "checkpoints", sa.Column("client_report_id", UUID(as_uuid=True), nullable=True)
    )
    op.add_column(
        "checkpoints",
        sa.Column(
            "phase_event_id", UUID(as_uuid=True),
            sa.ForeignKey("phase_events.id"), nullable=True,
        ),
    )
    op.create_index(
        _CHECKPOINT_REPORT_ID_INDEX,
        "checkpoints",
        ["trip_id", "client_report_id"],
        unique=True,
        postgresql_where=sa.text("client_report_id IS NOT NULL"),
    )

    # ── exceptions ───────────────────────────────────────────────────────────
    op.add_column("exceptions", sa.Column(_ASSESSMENT_COLUMN, JSONB, nullable=True))

    # R13/Task 5: one DRIVER_VEHICLE_SEPARATION finding per source event. Scoped to
    # this exception_type only (never broadened) so GPS_MISMATCH — which can
    # legitimately coexist with a separation finding on the very same phase_event_id
    # — keeps allowing as many rows as it always has.
    op.create_index(
        _PHASE_SEPARATION_INDEX,
        "exceptions",
        ["phase_event_id", "exception_type"],
        unique=True,
        postgresql_where=sa.text(
            "exception_type = 'driver_vehicle_separation' AND phase_event_id IS NOT NULL"
        ),
    )
    op.create_index(
        _CHECKPOINT_SEPARATION_INDEX,
        "exceptions",
        ["checkpoint_id", "exception_type"],
        unique=True,
        postgresql_where=sa.text(
            "exception_type = 'driver_vehicle_separation' AND checkpoint_id IS NOT NULL"
        ),
    )


def downgrade() -> None:
    op.drop_index(_CHECKPOINT_SEPARATION_INDEX, table_name="exceptions")
    op.drop_index(_PHASE_SEPARATION_INDEX, table_name="exceptions")
    op.drop_column("exceptions", _ASSESSMENT_COLUMN)

    op.drop_index(_CHECKPOINT_REPORT_ID_INDEX, table_name="checkpoints")
    op.drop_column("checkpoints", "phase_event_id")
    op.drop_column("checkpoints", "client_report_id")
    op.drop_column("checkpoints", _ASSESSMENT_COLUMN)

    op.drop_column("phase_events", "location_warning_reason")
    op.drop_column("phase_events", "location_warning_acknowledged_at")
    op.drop_column("phase_events", _ASSESSMENT_COLUMN)
