"""unique waybill reference on consignments — one waybill, one trip (FP-138)

A Parcel Perfect waybill identifies physical cargo, and cargo is on exactly one
trip. Until now nothing in the schema said so: consignment_service's
select-then-insert found no existing row, inserted, and two dispatchers citing
the same waybill at the same moment each got a trip. Both trips then anchored
their own journey-lock hash over the same freight — two contradictory records on
an append-only ledger, which is not something a later fix can take back.

The application-side guard (the reassignment check and the row lock in
fetch_and_sync_consignment) closes the window where a row already exists. It
cannot close the window where none does yet — there is nothing to lock until
someone has inserted. That case is what this constraint is for.

Hand-written rather than autogenerated on purpose: `alembic revision
--autogenerate` against the shared dev database currently reports a large
baseline drift (indexes present in the DB that the models do not declare, plus
foreign-key differences), so an autogenerated revision here would have dropped
roughly a dozen live indexes alongside this one-line change.

Verified before writing: the dev database held 26 consignment rows and zero
duplicate parcel_perfect_reference values, so this applies without a data
migration. Re-check before applying to any other environment — upgrade() fails
loudly on pre-existing duplicates rather than deleting anything, which is the
correct outcome: which of two trips owns a consignment is an operational
decision, not one a migration should make silently.

Revision ID: ciaran_uniq_waybill_ref
Revises: tim_user_sessions
Create Date: 2026-08-26
"""
from alembic import op

# Keep revision ids under 32 characters: alembic_version.version_num is
# varchar(32), and a longer id lets the DDL succeed and then fails on the
# version bump, rolling the whole migration back with a confusing error.
revision = "ciaran_uniq_waybill_ref"
down_revision = "tim_user_sessions"
branch_labels = None
depends_on = None

_CONSTRAINT_NAME = "uq_consignments_parcel_perfect_reference"


def upgrade() -> None:
    op.create_unique_constraint(
        _CONSTRAINT_NAME, "consignments", ["parcel_perfect_reference"]
    )


def downgrade() -> None:
    op.drop_constraint(_CONSTRAINT_NAME, "consignments", type_="unique")
