"""FP-280: every exception is reviewed — claim columns, needs_review default, backfill.

Adds exceptions.claimed_by_user_id / claimed_at (who is working an exception, and
since when), makes needs_review the column default, and moves every row that was only
ever "recorded" into the review inbox. Reviewed rows are untouched: their review is the
record.

Hand-written, not autogenerated: against this project autogenerate proposes dropping
live indexes and the Supabase auth FKs.

Revision ID: ciaran_exception_claims
Revises: ciaran_trailer_geofence
Create Date: 2026-09-30
"""
from alembic import op
import sqlalchemy as sa

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_exception_claims"
down_revision = "ciaran_trailer_geofence"
branch_labels = None
depends_on = None

_TABLE = "exceptions"
_CLAIMED_BY_FK = "fk_exceptions_claimed_by_user_id"


def upgrade() -> None:
    op.add_column(_TABLE, sa.Column("claimed_by_user_id", sa.UUID(), nullable=True))
    op.add_column(_TABLE, sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(_CLAIMED_BY_FK, _TABLE, "users", ["claimed_by_user_id"], ["id"])
    # A future write site or seed script that omits review_status must still land in
    # the inbox: the default is the last line of defence for "nothing is silently recorded".
    op.alter_column(_TABLE, "review_status", server_default="needs_review")
    op.execute("UPDATE exceptions SET review_status = 'needs_review' WHERE review_status = 'recorded'")


def downgrade() -> None:
    # Author-reviewed notes did not exist before this revision; return them to the
    # pre-FP-280 shape (a recorded dispatcher note with no review).
    op.execute(
        "UPDATE exceptions SET review_status = 'recorded', review_outcome = NULL, "
        "reviewed_by_user_id = NULL, reviewed_at = NULL "
        "WHERE review_outcome = 'dispatcher_authored'"
    )
    # Lossy by necessity: the backfill cannot tell a warning that was already
    # needs_review from one this revision moved, so every unreviewed non-critical row
    # returns to 'recorded' — which is exactly the pre-FP-280 policy.
    op.execute(
        "UPDATE exceptions SET review_status = 'recorded' "
        "WHERE review_status = 'needs_review' AND severity <> 'critical'"
    )
    op.alter_column(_TABLE, "review_status", server_default="recorded")
    op.drop_constraint(_CLAIMED_BY_FK, _TABLE, type_="foreignkey")
    op.drop_column(_TABLE, "claimed_at")
    op.drop_column(_TABLE, "claimed_by_user_id")
