"""tim close blockchain receipt fk drift

Revision ID: 8d6a2d9df9bc
Revises: de581e6a301b
Create Date: 2026-09-15 16:54:18.956571

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8d6a2d9df9bc'
down_revision: Union[str, Sequence[str], None] = 'de581e6a301b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_driver_events_blockchain_receipt', 'driver_events', 'blockchain_receipts', ['blockchain_receipt_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_driver_sub_blockchain_receipt', 'driver_substitutions', 'blockchain_receipts', ['blockchain_receipt_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_vehicle_events_blockchain_receipt', 'vehicle_events', 'blockchain_receipts', ['blockchain_receipt_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vehicle_events_blockchain_receipt', 'vehicle_events', type_='foreignkey')
    op.drop_constraint('fk_driver_sub_blockchain_receipt', 'driver_substitutions', type_='foreignkey')
    op.drop_constraint('fk_driver_events_blockchain_receipt', 'driver_events', type_='foreignkey')
    # ### end Alembic commands ###
