"""add exceptions.client_report_id + partial unique index per trip

Task 0B (FP-150 follow-up). Two problems close with this migration and the service
change it backs:

1. Nothing stopped a driver-raised exception from citing an EvidenceArtifact that
   belongs to a DIFFERENT trip — the FK only proves the artifact exists somewhere.
   Closed in orchestration/exception_service.py (checked in code, not here).

2. The driver-pwa's offline queue can retry a queued exception submission whose
   response was lost or never arrived (a network drop, a timeout) — and, before this
   column existed, that retry had no way to tell the server "this is the SAME report,
   not a new one". A resend could create a second TripException row, and — worse — a
   second uploaded photo, for one real-world incident.

`client_report_id` is the driver app's own stable id for one report: the offline
queue's entry UUID (lib/hooks/useOfflineQueue.ts), generated once when the report is
first queued and resent unchanged on every retry of that same entry. Nullable, with no
backfill: an exception raised before this column existed, or by an older installed
client that never sends it, genuinely has no such id, and inventing one would let a
stale row start colliding with a fresh one under the index below.

The uniqueness is scoped to (trip_id, client_report_id) rather than to
client_report_id alone — the id is a client-generated UUID with no server-wide
registry, so this only needs to rule out two ROWS ON THE SAME TRIP claiming one
report, not a global collision that can practically never happen anyway.

Partial (client_report_id IS NOT NULL): rows with no id carry no idempotency claim,
so they must never collide with each other or force NULL-handling readers to treat
"no id sent" as if it meant something.

Hand-written, not autogenerated — matching every other migration on this branch (see
2026_08_26_ciaran_uniq_active_order_no.py): autogenerate against the shared dev
database currently proposes dropping roughly a dozen live indexes.

Revision ID: ciaran_exc_idempotency
Revises: ciaran_corr_capture_time
Create Date: 2026-09-06
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_exc_idempotency"
down_revision = "ciaran_corr_capture_time"
branch_labels = None
depends_on = None

_COLUMN = "client_report_id"
_INDEX_NAME = "uq_exceptions_trip_client_report_id"


def upgrade() -> None:
    op.add_column(
        "exceptions", sa.Column(_COLUMN, UUID(as_uuid=True), nullable=True)
    )
    op.create_index(
        _INDEX_NAME,
        "exceptions",
        ["trip_id", _COLUMN],
        unique=True,
        postgresql_where=sa.text(f"{_COLUMN} IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(_INDEX_NAME, table_name="exceptions")
    op.drop_column("exceptions", _COLUMN)
