"""unique registration and driver ID number within an organisation

Both create paths already caught a unique violation and returned a 409 naming these
fields, but neither constraint existed. Duplicates were accepted outright — no
concurrency required, just the same form submitted twice. On vehicles the effect was
worse than a missing rule: the only constraint that did exist,
(organization_id, pulsit_device_id), was reported to the dispatcher as a duplicate
*registration*, so a double-assigned tracker sent them to correct a plate that was
perfectly fine.

Scoped per organisation, matching the existing uq_vehicles_org_pulsit. A licence plate
and an SA ID number are nationally unique in the real world, but FreightProof does not
model a vehicle or driver moving between operators yet. Org scope enforces the rule
that matters today and leaves that door open; widening later is an index swap, not a
data migration.

Verified before writing, against dev: 6 vehicles and 5 drivers, with zero duplicate
(organization_id, registration) pairs, zero duplicate id_numbers and zero duplicate
phone numbers. Applies with no data migration. Re-check before applying elsewhere —
upgrade() fails loudly on pre-existing duplicates rather than deleting anything.

Hand-written, not autogenerated: `alembic revision --autogenerate` against the shared
dev database currently proposes dropping roughly a dozen live indexes.

Revision ID: ciaran_uniq_fleet_ids
Revises: ciaran_uniq_order_no
Create Date: 2026-08-26
"""
from alembic import op

# Under 32 characters — alembic_version.version_num is varchar(32), and a longer id
# lets the DDL succeed then fails on the version bump, rolling the whole thing back.
revision = "ciaran_uniq_fleet_ids"
down_revision = "ciaran_uniq_order_no"
branch_labels = None
depends_on = None

_VEHICLES_CONSTRAINT = "uq_vehicles_org_registration"
_DRIVERS_CONSTRAINT = "uq_drivers_org_id_number"


def upgrade() -> None:
    op.create_unique_constraint(
        _VEHICLES_CONSTRAINT, "vehicles", ["organization_id", "registration"]
    )
    op.create_unique_constraint(
        _DRIVERS_CONSTRAINT, "drivers", ["organization_id", "id_number"]
    )


def downgrade() -> None:
    op.drop_constraint(_DRIVERS_CONSTRAINT, "drivers", type_="unique")
    op.drop_constraint(_VEHICLES_CONSTRAINT, "vehicles", type_="unique")
