"""Close the Supabase Data API on every table 0003 never covered.

0003_tom_rls_policies enabled row-level security on every table that existed in May,
which is what keeps the PostgREST Data API (the anon and authenticated roles) out of
them. Every table added since was created without RLS, and Supabase's default
privileges grant each new public table to anon and authenticated in full. Measured on
a freshly migrated project on 2026-09-23, these tables were readable AND writable by
anyone holding the publishable key, which ships inside both frontend bundles:
receiver identity checks, driver GPS trails, session records, handover tokens, the
fleet evidence event logs, and alembic_version itself.

Three changes, all aimed at the API roles only:
  1. Enable RLS on each table below with no policies, so the Data API sees nothing.
  2. Revoke every existing privilege anon and authenticated hold on them.
  3. Revoke Supabase's default grants for tables and sequences created from now on,
     so the next new table starts closed instead of open. This is the root cause.

Nothing in the application uses the Data API: the frontends use Supabase for login
only, and FastAPI connects as the table owner, which RLS does not restrict (no
FORCE ROW LEVEL SECURITY here). Behaviour is unchanged for every real caller.

Role statements are guarded on the role existing, as in the analytics migrations, so
they are a no-op on plain Postgres (the test database, a local instance).

Hand-written, not autogenerated: autogenerate cannot see RLS or grants, and against
this project it proposes dropping the Supabase auth FKs.

Revision ID: ciaran_lock_down_data_api
Revises: tim_driver_location_mismatch
Create Date: 2026-09-23
"""
from alembic import op

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "ciaran_lock_down_data_api"
down_revision = "tim_driver_location_mismatch"
branch_labels = None
depends_on = None

# Supabase's PostgREST roles. service_role and the table owner are deliberately
# untouched: they are how the backend and migrations reach the database.
API_ROLES: tuple[str, ...] = ("anon", "authenticated")

# Every public table without RLS on 2026-09-23. The analytics views are not listed:
# their own migrations already revoke the API roles, and RLS cannot apply to a view.
LOCKED_DOWN_TABLES: tuple[str, ...] = (
    "alembic_version",
    "driver_events",
    "driver_sessions",
    "handover_capability_tokens",
    "handover_confirmations",
    "handover_token_attempts",
    "idvs_quota_ledger",
    "precinct_events",
    "receiver_identity_verifications",
    "trip_location_pings",
    "trip_stops",
    "user_sessions",
    "vehicle_events",
)

_QUALIFIED_TABLES = ", ".join(f"public.{table}" for table in LOCKED_DOWN_TABLES)
_ROLE_ARRAY = ", ".join(f"'{role}'" for role in API_ROLES)


def _for_each_api_role(statement_template: str) -> str:
    """Run a %I-templated statement once per API role that exists on this server."""
    return f"""
DO $$
DECLARE
    api_role text;
BEGIN
    FOREACH api_role IN ARRAY ARRAY[{_ROLE_ARRAY}] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('{statement_template}', api_role);
        END IF;
    END LOOP;
END $$
"""


UPGRADE_STATEMENTS: tuple[str, ...] = (
    *(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY" for table in LOCKED_DOWN_TABLES),
    _for_each_api_role(f"REVOKE ALL ON {_QUALIFIED_TABLES} FROM %I"),
    _for_each_api_role("ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I"),
    _for_each_api_role("ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I"),
)

# Restores exactly the state before upgrade: Supabase's default grants and no RLS.
DOWNGRADE_STATEMENTS: tuple[str, ...] = (
    _for_each_api_role("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO %I"),
    _for_each_api_role("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO %I"),
    _for_each_api_role(f"GRANT ALL ON {_QUALIFIED_TABLES} TO %I"),
    *(f"ALTER TABLE public.{table} DISABLE ROW LEVEL SECURITY" for table in LOCKED_DOWN_TABLES),
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
