"""add handover_capability_tokens + handover_token_attempts (FP-236)

FP-155's receiver QR handover needs a token FreightProof can prove was never guessed
and was spent exactly once. Two tables:

`handover_capability_tokens` — one row per issued grant, bound to the phase event
(and, denormalised, its trip and stop) it confirms. The raw token is never stored,
only its SHA-256 hash, for the same reason Supabase's own session tokens are handled
as opaque strings rather than reconstructible values (see db/models/sessions.py).
Redemption is `redeemed_at IS NOT NULL` — no separate status column — because the
atomic gate in orchestration/handover_service.redeem_capability_token is a single
conditional `UPDATE ... WHERE redeemed_at IS NULL AND expires_at > now()`, and a
second status column would just be a second place that answer could drift from.

`handover_token_attempts` — every redemption attempt, accepted or rejected, per the
ticket's requirement that a rejected attempt is itself evidence. `token_id` is
nullable so an attempt against a token that never existed (an UNKNOWN presented hash)
is still recorded, against whatever trip/stop was presented.

Hand-written, not autogenerated — matching every other migration on this branch (see
2026_08_26_ciaran_uniq_active_order_no.py): autogenerate against the shared dev
database currently proposes dropping roughly a dozen live indexes.

Revision ID: tim_handover_tokens
Revises: tom_analytics_read_models
Create Date: 2026-09-10
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# Keep revision ids under 32 characters — alembic_version.version_num is varchar(32).
revision = "tim_handover_tokens"
down_revision = "tom_analytics_read_models"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "handover_capability_tokens",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("phase_event_id", UUID(as_uuid=True), sa.ForeignKey("phase_events.id"), nullable=False),
        sa.Column("trip_id", UUID(as_uuid=True), sa.ForeignKey("trips.id"), nullable=False),
        sa.Column("trip_stop_id", UUID(as_uuid=True), sa.ForeignKey("trip_stops.id"), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), onupdate=sa.text("now()"), nullable=False,
        ),
    )
    op.create_index(
        "uq_handover_capability_tokens_token_hash",
        "handover_capability_tokens", ["token_hash"], unique=True,
    )
    op.create_index(
        "ix_handover_capability_tokens_phase_event", "handover_capability_tokens", ["phase_event_id"],
    )

    op.create_table(
        "handover_token_attempts",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "token_id", UUID(as_uuid=True),
            sa.ForeignKey("handover_capability_tokens.id"), nullable=True,
        ),
        sa.Column("presented_trip_id", UUID(as_uuid=True), nullable=False),
        sa.Column("presented_trip_stop_id", UUID(as_uuid=True), nullable=False),
        sa.Column("rejection_reason", sa.String(30), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index(
        "ix_handover_token_attempts_token_id", "handover_token_attempts", ["token_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_handover_token_attempts_token_id", table_name="handover_token_attempts")
    op.drop_table("handover_token_attempts")
    op.drop_index("ix_handover_capability_tokens_phase_event", table_name="handover_capability_tokens")
    op.drop_index("uq_handover_capability_tokens_token_hash", table_name="handover_capability_tokens")
    op.drop_table("handover_capability_tokens")
