"""B1 — API contract: routes, methods, request/response schemas and status codes must not change.

The OpenAPI document is generated by a child process with settings pinned (see
_probe_runner.py) so it is identical on every machine. A pure move or split of backend
code must leave this snapshot untouched; an intended API change regenerates it with
UPDATE_SNAPSHOTS=1 (see _snapshot.py) and the git diff is the review.

Routes that exist ONLY when dev tooling is enabled (DEV_PANEL_ENABLED, and for the
truck/rig routes also PULSE_USE_MOCK) are kept out of the main snapshot and pinned
separately, so a refactor of the dev package cannot hide behind "dev only".
"""

from typing import Any

from tests.baseline._probe_runner import run_probe
from tests.baseline._snapshot import assert_matches_snapshot


def _dev_additions(without_dev: dict[str, Any], with_dev: dict[str, Any]) -> dict[str, Any]:
    """Operations and schemas present with dev tooling on but absent with it off."""
    paths: dict[str, Any] = {}
    for path, item in with_dev["paths"].items():
        existing = without_dev["paths"].get(path, {})
        added = {method: op for method, op in item.items() if method not in existing}
        if added:
            paths[path] = added
    base_schemas = without_dev.get("components", {}).get("schemas", {})
    schemas = {
        name: schema
        for name, schema in with_dev.get("components", {}).get("schemas", {}).items()
        if name not in base_schemas
    }
    return {"paths": paths, "schemas": schemas}


def test_openapi_document_matches_committed_snapshot() -> None:
    document = run_probe(False)["openapi"]

    assert_matches_snapshot("openapi.json", document)


def test_dev_tooling_only_adds_to_the_api_and_matches_committed_snapshot() -> None:
    without_dev = run_probe(False)["openapi"]
    with_dev = run_probe(True)["openapi"]

    additions = _dev_additions(without_dev, with_dev)

    # Dev tooling must be purely additive: switching it on may never change or remove a
    # production route, otherwise the main snapshot would not describe production.
    for path, item in without_dev["paths"].items():
        for method, operation in item.items():
            assert with_dev["paths"][path][method] == operation, f"{method.upper()} {path} differs with dev tooling on"
    assert additions["paths"], "expected dev tooling to register at least one route"
    assert_matches_snapshot("openapi.dev_additions.json", additions)
